language: go
go:
  - 1.13
  - tip
sudo: false
install:
  - go get github.com/mattn/go-runewidth
  - go get github.com/pkg/errors
  - go get github.com/sirupsen/logrus
  - go get golang.org/x/crypto/ssh/terminal
  - go get golang.org/x/oauth2
  - go get golang.org/x/text/encoding
  - go get google.golang.org/api/gmail/v1
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq gnupg
